### ISSUE TITLE
Upcoming linter changes

### ISSUE THREAD

**Issue by AsaAyers** [josa42/atom-linter-handlebars#1]
We're in the process of replacing `linter` with a rewrite. Our central issue for tracking the plan is https://github.com/AtomLinter/linter-plus/issues/29. We're working hard to make this a smooth transition for you and for your users.

Please let us know here if you'd prefer to do the work yourself. If you have any questions or concerns please join us in our [room on gitter](https://gitter.im/AtomLinter/Linter).

**Comment by josa42** [comment]
Actually I am not sure what I have to do here. Right now it is a pretty simple package. Basically I am just providing a `cmd` and and a `regex`.

Is the Linter class going to be removed, so I have to spawn a process myself?

**Comment by AsaAyers** [comment]
@steelbrain ? What's the plan here? I know the base class as it is now will get rmoved once everyone is on the new API.

**Comment by steelbrain** [comment]
We had thought of putting a base-like class with a cleaner API in the AtomLinter/atom-linter repo and provide it as an npm package.

**Comment by josa42** [comment]
Sounds good. Let me know if I can help with that.
I'll try to reuse parts of Linter class from AtomLinter/linter and put in this repository for now.

**Comment by steelbrain** [comment]
Awesome, Thanks.
We haven't really discussed the new API of that package yet. when we do, I'll make sure to ping you in the gitter room.

**Comment by josa42** [comment]
I started working this: #2
