### ISSUE TITLE
Does it support .html files?

### ISSUE THREAD

**Issue by lehtu** [josa42/atom-linter-handlebars#39]

**Comment by josa42** [comment]
No, it doesn't. It supports [`.hbs` and `.handlebars` files](https://github.com/josa42/atom-linter-handlebars/blob/master/lib/linter-handlebars-provider.js#L10). Since this "linter" uses the [handlebars](https://github.com/wycats/handlebars.js) compiler, I don't see any benefit supporting `.html` files.

**Comment by lehtu** [comment]
Well Meteor uses Blaze which has variant of handlebars and in Meteor templates are saved as .html files. So that's why I was asking.

**Comment by josa42** [comment]
Ok, I get you point. But I don't like the idea to lint every html file, because usually they won't be handlebars files.

**Comment by josa42** [comment]
You could bind `.html` files to the handlebars / mustache grammar.

You can do that manually...

![kapture 2017-06-20 at 22 14 55](https://user-images.githubusercontent.com/423234/27353872-fb3301cc-5605-11e7-97b8-0b31d31c7e86.gif)

... or permanently. To do this you add this to your `~/.atom/config.cson` (macOS)

```
"*":
  core:
    customFileTypes:
      "text.html.mustache": [
        "html"
      ]
```

See: [Atom Documentation: Customizing Language Recognition](http://flight-manual.atom.io/using-atom/sections/basic-customization/#customizing-language-recognition)

This would make imply that `linter-handlebars` runs an these files. And as a side effect it also highlights handlebar tags correctly.

**Comment by josa42** [comment]
Actually the template engine for meteor / blaze seems to be called [spacebars](http://blazejs.org/api/spacebars.html), which I just added to the supported grammars. So if you install [`language-spacebars`](https://atom.io/packages/language-spacebars) it should work.

**Comment by lehtu** [comment]
Okay, thanks for the answers! :)
