### ISSUE TITLE
How does one go about getting this to work?

### ISSUE THREAD

**Issue by jfrux** [josa42/atom-linter-handlebars#40]

**Comment by jfrux** [comment]
Okay, restarted Atom and it seems to be working.  However, is there any inline tag completion highlighting and things? Do you know of something that does this?

I'd like to be able to see clearly if a tag isn't completed or something, like rogue tags, etc?

**Comment by josa42** [comment]
All this package does it running the code through [`Handlebars.precompile()`](https://github.com/josa42/atom-linter-handlebars/blob/master/lib/linter-handlebars-provider.js#L36), and returning the errors that occur.
